export const applyPdfHeaderAndFooter = async (doc, title, userObj = null) => {
  // Try to load the logo image
  const loadLogo = () => {
    return new Promise((resolve) => {
      const img = new Image();
      img.src = '/logo.png';
      img.onload = () => resolve(img);
      img.onerror = () => resolve(null);
    });
  };

  const logoImg = await loadLogo();
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // HEADER
    // 1. Logo Background & Text
    if (logoImg) {
      // If logo image exists, draw it. (Width 40mm, Height 12mm approx)
      doc.addImage(logoImg, 'PNG', margin, 10, 40, 12);
    } else {
      // Fallback if logo.png is not found
      doc.setFillColor(29, 78, 216); // Blue-700
      doc.roundedRect(margin, 10, 16, 16, 3, 3, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('K', margin + 8, 22, { align: 'center' });
      
      doc.setTextColor(29, 78, 216);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('KRAVI', margin + 20, 18);
      
      doc.setTextColor(100, 100, 100);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text('Sales Person Tracker', margin + 20, 24);
    }

    // 3. Center Title & Date
    doc.setTextColor(30, 58, 138); // Darker blue
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(title, pageWidth / 2, 18, { align: 'center' });
    
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on: ${new Date().toLocaleString('en-IN')}`, pageWidth / 2, 24, { align: 'center' });

    // 4. Contact info Top Right (Logged in user details)
    const rightCol = pageWidth - margin;
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(userObj?.name || 'Super Admin', rightCol, 12, { align: 'right' });
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    if (userObj?.role) {
      doc.text(`Role: ${userObj.role.charAt(0).toUpperCase() + userObj.role.slice(1)}`, rightCol, 16, { align: 'right' });
    }
    if (userObj?.email) {
      doc.text(`Email: ${userObj.email}`, rightCol, 20, { align: 'right' });
    }
    if (userObj?.mobile) {
      doc.text(`Phone: ${userObj.mobile}`, rightCol, 24, { align: 'right' });
    }

    // 5. Blue line below header
    doc.setDrawColor(29, 78, 216);
    doc.setLineWidth(0.5);
    doc.line(margin, 30, rightCol, 30);

    // FOOTER
    const footerY = pageHeight - 15;
    
    // 6. Blue line above footer
    doc.line(margin, footerY - 5, rightCol, footerY - 5);
    
    // 7. Footer Text
    doc.setTextColor(29, 78, 216);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(`Generated By : ${userObj?.name || 'Super Admin'}`, margin, footerY + 2);
    
    doc.setTextColor(50, 50, 50);
    doc.setFont('helvetica', 'normal');
    doc.text('This is a system generated report.', pageWidth / 2, footerY + 2, { align: 'center' });
    
    doc.setTextColor(29, 78, 216);
    doc.setFont('helvetica', 'bold');
    doc.text(`Page ${i} of ${pageCount}`, rightCol, footerY + 2, { align: 'right' });
  }

  // Restore defaults
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
};
