import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

const BLUE  = [26, 86, 219];
const DBLUE = [30, 58, 138];
const GRAY  = [107, 114, 128];
const DARK  = [17, 24, 39];
const WHITE = [255, 255, 255];

/** Draws the shared KRAVI letterhead on `doc` and returns the Y position after the divider. */
const drawPDFHeader = (doc, title, subtitle) => {
  const W = doc.internal.pageSize.getWidth();
  const R = W - 14;
  const L = 14;

  // Logo block
  doc.setFillColor(...BLUE);
  doc.roundedRect(L, 12, 32, 32, 5, 5, 'F');
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text('K', L + 8, 12 + 24);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DBLUE);
  doc.text('KRAVI', L + 40, 12 + 16);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text('Sales Person Tracker', L + 40, 12 + 24);

  // Center title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DBLUE);
  doc.text(title, W / 2, 12 + 16, { align: 'center' });

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(subtitle, W / 2, 12 + 26, { align: 'center' });

  // Contact right
  const cX = R;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK);
  doc.text('Kravi Infotech', cX, 12 + 10, { align: 'right' });

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  let yRight = 12 + 17;
  doc.text('Ahilyanagar, Maharashtra, India', cX, yRight, { align: 'right' });
  yRight += 7;
  doc.text('contact@kraviinfotech.com', cX, yRight, { align: 'right' });
  yRight += 7;
  doc.text('+91 9657013534', cX, yRight, { align: 'right' });

  // Divider
  const y = 12 + 40;
  doc.setDrawColor(...BLUE);
  doc.setLineWidth(1.2);
  doc.line(L, y, R, y);

  return y + 10;
};

/** Draws the shared footer on each PDF page. */
const drawPDFFooter = (doc, footerLeft) => {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const L = 14;
  const R = W - 14;
  const footerY = H - 15;

  doc.setDrawColor(...BLUE);
  doc.setLineWidth(1.2);
  doc.line(L, footerY - 10, R, footerY - 10);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLUE);
  doc.text(footerLeft, L, footerY);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...DARK);
  doc.text('This is a system generated report.', W / 2, footerY, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLUE);
  doc.text(
    `Page ${doc.internal.getCurrentPageInfo().pageNumber} of {total_pages_count_string}`,
    R,
    footerY,
    { align: 'right' }
  );
};

/**
 * Export manager-view records as a PDF.
 * @param {Array} records
 * @param {string} managerName
 */
export const exportManagerRecordsPDF = (records, managerName = 'Manager') => {
  if (!records.length) { alert('No data to export.'); return; }

  const doc = new jsPDF('landscape');
  const L = 14;
  const R = doc.internal.pageSize.getWidth() - 14;

  const dateStr = format(new Date(), 'dd/MM/yyyy, hh:mm a');
  const startY = drawPDFHeader(doc, 'Sales Records Report', `Generated on: ${dateStr}`);

  const columns = ['Date', 'Seller', 'Shop Name', 'Shop Type', 'Total Amount', 'Paid', 'Pending', 'Status'];
  const rows = records.map(r => [
    format(new Date(r.visitDatetime), 'dd/MM/yyyy HH:mm'),
    r.sellerId?.name || 'Unknown',
    r.shopName,
    r.shopType,
    `Rs. ${r.totalAmount}`,
    `Rs. ${r.paidAmount || 0}`,
    `Rs. ${r.pendingAmount || 0}`,
    r.paymentStatus || 'Pending',
  ]);

  autoTable(doc, {
    head: [columns],
    body: rows,
    startY,
    theme: 'grid',
    headStyles: { fillColor: DBLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold', halign: 'center' },
    bodyStyles: { fontSize: 8, textColor: [50, 50, 50] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { cellPadding: 4, halign: 'center', lineColor: [220, 225, 235] },
    margin: { left: L, right: L, bottom: 30 },
    didDrawPage: () => drawPDFFooter(doc, `Generated By : ${managerName}`),
  });

  if (typeof doc.putTotalPages === 'function') {
    doc.putTotalPages('{total_pages_count_string}');
  }
  doc.save(`Sales_Records_${new Date().toISOString().slice(0, 10)}.pdf`);
};

const safeDate = (v, full = false) => {
  try {
    const d = new Date(v);
    if (isNaN(d.getTime())) return 'N/A';
    return full
      ? d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) +
          ', ' + d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })
      : d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  } catch { return 'N/A'; }
};

/**
 * Export seller's own records as a PDF.
 * @param {Array} records
 */
export const exportSellerRecordsPDF = (records) => {
  if (!records.length) { alert('No records to export.'); return; }

  const doc = new jsPDF('landscape');
  const L = 14;
  const R = doc.internal.pageSize.getWidth() - 14;

  const subtitle = `Generated on: ${new Date().toLocaleString('en-IN')}  |  Total: ${records.length} visits`;
  const startY = drawPDFHeader(doc, 'My Sales Records', subtitle);

  const STATUS_COL = 8;
  const columns = ['#', 'Shop Name', 'Mobile', 'Visit Date & Time', 'Items', 'Total Amount', 'Paid', 'Pending', 'Status'];
  const rows = records.map((r, i) => {
    const itemCount = (r.items || []).reduce(
      (s, it) => s + (it.unit === 'weight' ? 1 : Number(it.quantity || 0)), 0
    );
    return [
      i + 1,
      r.shopName || '-',
      r.mobile   || '-',
      safeDate(r.visitDatetime, true),
      itemCount,
      `Rs. ${Number(r.totalAmount   || 0).toLocaleString('en-IN')}`,
      `Rs. ${Number(r.paidAmount    || 0).toLocaleString('en-IN')}`,
      `Rs. ${Number(r.pendingAmount || 0).toLocaleString('en-IN')}`,
      r.paymentStatus || 'Pending',
    ];
  });

  autoTable(doc, {
    head: [columns],
    body: rows,
    startY,
    theme: 'grid',
    headStyles: { fillColor: DBLUE, textColor: WHITE, fontSize: 8, fontStyle: 'bold', halign: 'center' },
    bodyStyles: { fontSize: 8, textColor: [50, 50, 50] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { cellPadding: 4, halign: 'center', lineColor: [220, 225, 235] },
    columnStyles: {
      1: { halign: 'left' },
      3: { halign: 'left' },
      5: { halign: 'right' },
      6: { halign: 'right', textColor: [5, 122, 85],  fontStyle: 'bold' },
      7: { halign: 'right', textColor: [185, 28, 28], fontStyle: 'bold' },
    },
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === STATUS_COL) {
        const val = String(data.cell.raw || '');
        if (val === 'Paid')         { data.cell.styles.textColor = [5, 122, 85];   data.cell.styles.fontStyle = 'bold'; }
        else if (val === 'Pending') { data.cell.styles.textColor = [185, 28, 28];  data.cell.styles.fontStyle = 'bold'; }
        else                        { data.cell.styles.textColor = [180, 83, 9];   data.cell.styles.fontStyle = 'bold'; }
      }
    },
    margin: { left: L, right: L, bottom: 30 },
    didDrawPage: () => drawPDFFooter(doc, 'KRAVI Sales Person Tracker'),
  });

  if (typeof doc.putTotalPages === 'function') {
    doc.putTotalPages('{total_pages_count_string}');
  }
  doc.save(`My_Records_${new Date().toISOString().slice(0, 10)}.pdf`);
};

/**
 * Export records as CSV.
 * @param {Array} records
 * @param {string} filenamePrefix  e.g. 'manager_records' or 'sales_report_weekly'
 */
export const exportRecordsCSV = (records, filenamePrefix = 'records') => {
  if (!records.length) { alert('No data to export.'); return; }

  const headers = [
    'Date', 'Seller', 'Shop Name', 'Shop Mobile', 'Shop Type', 'Address', 'Landmark',
    'Total Amount', 'Paid Amount', 'Pending Amount', 'Payment Status', 'Items Count',
    'Items (Product x Qty @ Rate)',
  ];

  const rows = records.map(r => {
    const itemsFormatted = r.items?.map(item => {
      if (item.unit === 'weight') return `${item.productName} (${item.weight} kg @ ₹${item.price})`;
      const rate = item.price || item.rate;
      return `${item.productName} (${item.quantity} pcs @ ₹${rate})`;
    }).join('; ') || '';

    return [
      new Date(r.visitDatetime).toISOString(),
      r.sellerId?.name || 'Unknown',
      `"${r.shopName.replace(/"/g, '""')}"`,
      `"${(r.mobile || '').replace(/"/g, '""')}"`,
      r.shopType,
      `"${r.shopAddress.replace(/"/g, '""')}"`,
      `"${(r.landmark || '').replace(/"/g, '""')}"`,
      r.totalAmount,
      r.paidAmount || 0,
      r.pendingAmount || 0,
      r.paymentStatus || 'Pending',
      r.items?.length || 0,
      `"${itemsFormatted.replace(/"/g, '""')}"`,
    ];
  });

  const csvContent = [headers.join(','), ...rows.map(e => e.join(','))].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url  = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filenamePrefix}_${new Date().toISOString().slice(0, 10)}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
