import React, { useEffect, useState } from 'react';
import { BarChart3, Download, FileText, Layers, PieChart, TrendingUp } from 'lucide-react';
import API from '../../api/axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const REPORT_CARDS=[
 {title:'Revenue Report',label:'Total income and earnings',icon:TrendingUp,bg:'bg-[#6C3EF4]'},
 {title:'Subscription Report',label:'Subscription plan analytics',icon:BarChart3,bg:'bg-[#10B981]'},
 {title:'Company Report',label:'Company-wise report',icon:FileText,bg:'bg-[#8B5CF6]'},
 {title:'Manager Report',label:'Manager performance report',icon:PieChart,bg:'bg-[#F59E0B]'},
 {title:'Renewal Report',label:'Upcoming renewals report',icon:Layers,bg:'bg-[#EF4444]'}
];
const formatCsvValue=v=>v==null?'':String(v).replace(/"/g,'""');
const buildCsvContent=records=>{const headers=['Date','Seller','Shop Name','Shop Type','Total Amount','Paid Amount','Pending Amount','Payment Status'];const rows=records.map(r=>[new Date(r.visitDatetime).toISOString(),r.sellerId?.name||'Unknown',`"${formatCsvValue(r.shopName)}"`,r.shopType,r.totalAmount,r.paidAmount||0,r.pendingAmount||0,r.paymentStatus||'Pending'].join(','));return [headers.join(','),...rows].join('\n');};
const exportCsvFile=(name,records)=>{const url=URL.createObjectURL(new Blob([buildCsvContent(records)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
const getCardValue=(title,s)=>({ 'Revenue Report':`₹${Number(s.yearlyTotal||0).toLocaleString('en-IN')}`,'Subscription Report':`${s.totalSellers||0} Sellers`,'Company Report':`${s.totalRecords||0} Records`,'Manager Report':`${s.totalSellers||0} Managers`,'Renewal Report':`${s.totalPending||0} Pending`}[title]||'N/A');

const ReportsHeader=({loading,records,reportName,onCSV,onPDF,info})=><div className="rounded-3xl border border-gray-100 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><h1 className="text-3xl font-bold">Reports</h1><p className="mt-2 text-gray-500">Generate and download business reports.</p>{info&&<p className="mt-3 text-sm text-slate-600">{info}</p>}</div><div className="flex flex-wrap items-center gap-3"><div className="rounded-3xl bg-gray-100 px-4 py-3 text-sm">{loading?'Loading report...':records.length?`${records.length} records loaded for ${reportName}`:'Generate a report to view records and exports'}</div><button type="button" onClick={onCSV} className="flex items-center gap-2 rounded-2xl border bg-white px-4 py-3"><Download size={16}/> CSV</button><button type="button" onClick={onPDF} className="flex items-center gap-2 rounded-2xl border bg-white px-4 py-3"><Download size={16}/> PDF</button></div></div></div>;
const ReportCards=({summary,onGenerate})=><div className="grid grid-cols-1 gap-4 xl:grid-cols-5">{REPORT_CARDS.map(card=>{const Icon=card.icon;return <div key={card.title} className="flex flex-col justify-between rounded-3xl border bg-white p-6 shadow-sm"><div><div className={`inline-flex rounded-3xl p-3 ${card.bg}`}><Icon size={20} className="text-white"/></div><p className="mt-5 text-sm text-gray-500">{card.title}</p><h3 className="mt-3 text-2xl font-bold">{getCardValue(card.title,summary)}</h3><p className="mt-2 text-sm text-gray-500">{card.label}</p></div><button type="button" onClick={()=>onGenerate(card.title)} className="mt-6 w-full rounded-2xl bg-[#6C3EF4] px-4 py-3 text-sm font-semibold text-white">Generate Report</button></div>})}</div>;
const ReportRecords=({records,activeFilter})=><div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-6"><div><h3 className="text-xl font-bold">Report Records</h3><p className="text-sm text-gray-500">{records.length} records found</p></div><div className="text-sm text-gray-500">Current report: {activeFilter}</div></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-500"><tr>{['Date','Seller','Shop Name','Type','Total','Paid','Pending'].map(h=><th key={h} className="px-6 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{records.length===0?<tr><td colSpan={7} className="px-6 py-10 text-center">No report records loaded yet.</td></tr>:records.map(r=><tr key={r._id} className="hover:bg-gray-50"><td className="px-6 py-4">{new Date(r.visitDatetime).toLocaleDateString('en-IN')}</td><td className="px-6 py-4">{r.sellerId?.name||'Unknown'}</td><td className="px-6 py-4">{r.shopName}</td><td className="px-6 py-4">{r.shopType}</td><td className="px-6 py-4">₹{r.totalAmount||0}</td><td className="px-6 py-4">₹{r.paidAmount||0}</td><td className="px-6 py-4">₹{r.pendingAmount||0}</td></tr>)}</tbody></table></div></div>;

const Reports=()=>{const [activeFilter,setActiveFilter]=useState('Revenue Report');const [summary,setSummary]=useState({totalSellers:0,totalRecords:0,monthlyTotal:0,yearlyTotal:0,totalPending:0});const [records,setRecords]=useState([]);const [loading,setLoading]=useState(false);const [reportName,setReportName]=useState('Revenue Report');const [infoMessage,setInfoMessage]=useState('');useEffect(()=>{API.get('/reports/summary').then(r=>setSummary(r.data)).catch(e=>console.error(e));},[]);const generate=async label=>{setLoading(true);setReportName(label);setActiveFilter(label);try{const [s,r]=await Promise.all([API.get('/reports/summary'),API.get('/reports/records')]);setSummary(s.data);setRecords(Array.isArray(r.data)?r.data:[]);setInfoMessage(`Loaded ${Array.isArray(r.data)?r.data.length:0} records for ${label}`);}catch(e){setInfoMessage(e.response?.data?.message||'Failed to generate report.');}finally{setLoading(false);}};const csv=()=>records.length?exportCsvFile(`${reportName.replace(/\s+/g,'_')}.csv`,records):alert('No records to export');const pdf=()=>{if(!records.length)return alert('No records to export');const doc=new jsPDF();autoTable(doc,{head:[['Date','Seller','Shop','Type','Total','Paid','Pending']],body:records.map(r=>[new Date(r.visitDatetime).toLocaleDateString('en-IN'),r.sellerId?.name||'Unknown',r.shopName,r.shopType,r.totalAmount||0,r.paidAmount||0,r.pendingAmount||0])});doc.save(`${reportName.replace(/\s+/g,'_')}.pdf`);};return <div className="space-y-6"><ReportsHeader loading={loading} records={records} reportName={reportName} onCSV={csv} onPDF={pdf} info={infoMessage}/><ReportCards summary={summary} onGenerate={generate}/><ReportRecords records={records} activeFilter={activeFilter}/></div>};
export default Reports;
